
ARG NODE_VERSION=16.13.1

FROM node:${NODE_VERSION}-alpine as build

WORKDIR /opt

COPY package.json tsconfig.json tsconfig.compile.json .barrelsby.json ./

RUN npm i

COPY ./src ./src
COPY ./secrets ./secrets

#CMD ["ls", "-la", "/opt/src"]
CMD ["npm", "run", "start"]

