version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '8083:8083'
    stdin_open: true
    tty: true
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
